version: "3.9"
services:
  redis:
    container_name: redis_service
    image: redis:latest
    networks:
      - my_network
  mongo:
    container_name: mongodb_service
    image: mongo:latest
    networks:
      - my_network
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
    ports:
      - "3000:3000"
    networks:
      - my_network
    volumes:
      - C:\Users\Thiha\OneDrive\Desktop\hello-wops-main\logs:/app/logs
    restart: always
    links:
      - "mongo:mongodb"
      - "redis:redisdb"
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REDIS_HOST=redisdb
      - REDIS_PORT=6379
networks:
  my_network:
    driver: bridge